# Manipulación de Datos con Numpy

# NumPy 

NumPy (o Numpy) es una biblioteca de álgebra lineal para Python, la razón por la que es tan importante para la ciencia de datos con Python es que casi todas las bibliotecas del ecosistema PyData se basan en NumPy como uno de sus principales componentes básicos.

Numpy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C. Para obtener más información sobre por qué querría usar Arrays en lugar de listas, consulte esta excelente [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Solo aprenderemos los conceptos básicos de NumPy, ¡para comenzar necesitamos instalarlo!


## Instrucciones de instalación

**Se recomienda encarecidamente que instale Python utilizando la distribución de Anaconda para asegurarse de que todas las dependencias subyacentes (como las bibliotecas de Álgebra lineal) se sincronicen con el uso de una instalación de conda. Si tiene Anaconda, instale NumPy yendo a su terminal o símbolo del sistema y escribiendo:**
    
    conda install numpy
    
**Si no tiene Anaconda y no puede instalarlo, consulte [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**


## Usando NumPy

Una vez que haya instalado NumPy, puede importarlo como una biblioteca:

In [1]:
import numpy as np

Numpy tiene muchas funciones y capacidades integradas. No los cubriremos todos, sino que nos centraremos en algunos de los aspectos más importantes de Numpy: vectores, arreglos, matrices y generación de números. Comencemos discutiendo los arreglos.

# Arreglos Numpy

Los arreglos NumPy son la principal forma en que usaremos Numpy a lo largo del curso. Las arreglos Numpy vienen esencialmente en dos sabores: vectores y matrices. Los vectores son estrictamente matrices de 1-dimensión y las matrices son de 2 o más -dimensiones (pero debe tener en cuenta que una matriz todavía puede tener solo una fila o una columna).

Comencemos nuestra introducción explorando cómo crear arreglos NumPy.

## Creación de arreglos NumPy

### desde una lista de Python

Podemos crear un arreglo convirtiendo directamente una lista o lista de listas:

In [2]:
#crea un arreglo del 10 al 50 que van incrementando de 2 en 2
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [3]:
mi_lista = [1,2,3]
mi_lista

[1, 2, 3]

In [4]:
#Convirtiendo la lista en vectores
np.array(mi_lista)

array([1, 2, 3])

In [5]:
mi_matriz = [[1,2,3],[4,5,6],[7,8,9]]
mi_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(mi_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#crea un arreglo de 0 a 1 de 12 numeros separados con el mismo espacio linealmente
np.linspace(0,1,12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [8]:
#genera un numero aleatorio
np.random.rand(1)

array([0.94716751])

In [9]:
#genera 25 numeros aleatorios con distribucion normal estandar
np.random.randn(25)

array([ 1.60563179,  0.8195339 ,  0.00523013, -0.4942637 ,  0.68989576,
        0.06394292, -0.35053035, -1.09813479, -0.55044177, -0.68174149,
       -1.21008689,  0.17529476,  0.04068512, -0.41297103,  0.03626985,
       -0.23282242, -1.33028409, -1.24140425, -0.43685664,  0.22700582,
        1.27777151,  2.12806403,  0.77588043, -1.64834741,  0.90122464])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar sus ubicaciones de índice usando argmin o argmax

In [10]:
#genera 10 valores aleatorios enteros entre 0 y 50
ranarr = np.random.randint(0,50,10)

In [11]:
ranarr

array([20, 32, 15, 47,  8, 43, 28, 37,  0, 20])

In [12]:
ranarr.max()

47

In [13]:
#indice/posicion del valor maximo
ranarr.argmax()

3

In [14]:
ranarr.min()

0

In [15]:
ranarr.min()

0


## Forma

La forma es un atributo que tienen los arreglos (no un método):

In [16]:
arr = np.arange(25)

In [17]:
#arreglo de vectores, los vectores son punto en un espacio, no tienen filas ni columnas, solo valores
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
# Vectores fiese que solo me dice 25,
arr.shape

(25,)

In [19]:
# Observe los dos conjuntos de corchetes que significan que esto ahora es un arreglo porque tiene 1 fila y 25 columnas
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [20]:
arr.reshape(1,25).shape

(1, 25)

In [21]:
#este es un arreglo de 25 filas y 1 columna
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [22]:
arr.reshape(25,1).shape

(25, 1)


## Indexación y selección
La forma más sencilla de elegir uno o algunos elementos de una matriz es muy similar a las listas de Python:

In [23]:
#Obtenga un valor en un índice
arr[8]

8

In [24]:
#Obtenga un valor de un rango
arr[1:5]

array([1, 2, 3, 4])

In [25]:
#Obtenga un valor de un rango
arr[0:5]

array([0, 1, 2, 3, 4])

In [26]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Mostrar
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
#Indexación de filas
arr_2d[1]


array([20, 25, 30])

In [28]:
# El formato es arr_2d [fila] [col] o arr_2d [fila, col]

# Obtener valor de elemento individual fila 2 columna 1
arr_2d[1][0]

20

In [29]:
# Obtener valor de elemento individual
arr_2d[1,0]

20

In [30]:
# Corte de matriz 2D

#Forma (2,2) desde la esquina superior derecha
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
#Forma fila inferior
arr_2d[2]

array([35, 40, 45])

In [32]:
#Forma fila inferior
arr_2d[2,:]

array([35, 40, 45])

## Funciones de matriz universal

Numpy viene con muchas [funciones de matriz universales](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), que son esencialmente operaciones matemáticas que puede utilizar para realizar la operación en toda la matriz. Muestremos algunos comunes:

In [33]:
# Tomando raíces cuadradas
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [34]:
#Calcular exponencial (e ^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [35]:
np.max(arr) #igual que arr.max()

24

In [36]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [37]:
np.log(arr)

<ipython-input-37-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [38]:
np.nan

nan