# Clase 2023-11-13

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [111]:
y = np.random.rand(6)
y*5

array([2.05747385, 4.24411235, 1.29157854, 4.15225734, 0.68407142,
       2.62972207])

In [120]:
opciones_cena = ['Hamburguesa', 'Pollo', 'Lasaña', 'Filet Mignon']
np.random.choice(opciones_cena)

'Pollo'

In [123]:
cantidad = [17,40,1]
precio = [2,1,10]
#No podemos multiplicar estas listas

In [124]:
calorias_por_servicio = np.array([740,240,408,301])

In [215]:
precios = np.array([8.5,12.5,11.,15.75])

In [169]:
porciones = np.array([3,0,2,1])

In [128]:
calorias_total = calorias_por_servicio * porciones
np.sum(calorias_total)

3337

In [129]:
precio_total = precios * porciones
np.sum(precio_total)

63.25

In [130]:
arreglo_opciones = np.array(opciones_cena)
arreglo_opciones

array(['Hamburguesa', 'Pollo', 'Lasaña', 'Filet Mignon'], dtype='<U12')

In [131]:
for indice,plato in enumerate(arreglo_opciones):
    print(f'{indice}: {plato}')

0: Hamburguesa
1: Pollo
2: Lasaña
3: Filet Mignon


In [135]:
def reporte_opciones_comida():
    """Esta función imprime un menú que muestra el índice de cada comida en el arreglo de opciones"""
    for indice,plato in enumerate(arreglo_opciones):
        print(f'{indice}: {plato}')

In [132]:
porciones

array([3, 0, 2, 1])

In [133]:
porciones[1] =2

In [134]:
porciones

array([3, 2, 2, 1])

In [136]:
reporte_opciones_comida?

In [216]:
precio_total = precios * porciones
np.sum(precio_total)

63.25

In [218]:
cena_data = {'Opciones de cena': arreglo_opciones,
            'Precios': precios,
            'Calorias por Servicio': calorias_por_servicio,
            'Descuento' : np.array([0.25,0,0,0.25]),
            'Porciones': porciones}
cena_data

{'Opciones de cena': array(['Hamburguesa', 'Pollo', 'Lasaña', 'Filet Mignon'], dtype='<U12'),
 'Precios': array([ 8.5 , 12.5 , 11.  , 15.75]),
 'Calorias por Servicio': array([740, 240, 408, 301]),
 'Descuento': array([0.25, 0.  , 0.  , 0.25]),
 'Porciones': array([3, 0, 2, 1])}

In [219]:
import pandas as pd

In [220]:
df = pd.DataFrame(cena_data)
df

Opciones de cena  Precios  Calorias por Servicio  Descuento  Porciones
0      Hamburguesa     8.50                    740       0.25          3
1            Pollo    12.50                    240       0.00          0
2           Lasaña    11.00                    408       0.00          2
3     Filet Mignon    15.75                    301       0.25          1

In [221]:
(df['Precios'] - df['Precios']*df['Descuento']) * df['Porciones']

0    19.1250
1     0.0000
2    22.0000
3    11.8125
dtype: float64

# Series

In [222]:
etiquetas = ['a', 'b','c']
mi_lista = [10,20,30]
arr = np.array(mi_lista)
d = {'a':10, 'b':20, 'c':30}

In [223]:
pd.Series(mi_lista)

0    10
1    20
2    30
dtype: int64

In [224]:
pd.Series(data = mi_lista, index = etiquetas)

a    10
b    20
c    30
dtype: int64

In [225]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [228]:
ser1 = pd.Series(data = [1,2,3,4], index = ['USA', 'Alemania', 'Ucrania', 'Japón'])
ser1

USA         1
Alemania    2
Ucrania     3
Japón       4
dtype: int64

In [229]:
ser2 = pd.Series(data = [1,2,5,4], index = ['USA', 'Alemania', 'Italia', 'Japón'])
ser2

USA         1
Alemania    2
Italia      5
Japón       4
dtype: int64

In [230]:
ser2['USA']

1

In [232]:
ser2[2]

5

In [233]:
ser2['Italia']

5

In [234]:
ser1 + ser2

Alemania    4.0
Italia      NaN
Japón       8.0
USA         2.0
Ucrania     NaN
dtype: float64

# Métodos integrados de cálculos

In [235]:
ser1.count()

4

In [236]:
ser2.sum()

12

In [237]:
ser1.mean()

2.5

In [240]:
ser1.median()

2.5

# Data Frames

In [254]:
matriz = np.random.randn(5,4)

In [255]:
columnas = ['a','b','c','d']
indice = ['e','f','g','h','i']

In [264]:
matriz_df = pd.DataFrame(matriz, indice, columnas)
matriz_df

a         b         c         d
e  0.416521 -0.708704 -0.146177  2.322912
f -0.904858 -1.060373  0.667033 -0.039637
g -0.007392 -0.759991  0.265387  2.106834
h  1.464881 -0.432266  1.239782 -0.327442
i -0.693036 -3.502554  1.038166 -0.752953

# Conectando a fuentes de datos

In [ ]:
df_csv = pd.read_csv()